### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by dannyfritz** [bhuber2010/gSchool_Personal-Profile-Site#1]
Pretty fun click events you have on your text sections.

What types of home automation have you done so far?

There are opportunities for sustainability in the programming world. [Tendril](https://www.tendrilinc.com/) is a local startup hiring developers for their mission.

Also, I love seeing `display: flex` being used. It is a pretty new CSS property, but it is very powerful and clean.

**Comment by bhuber2010** [comment]
For home automation, mostly Smartthings based Z-wave stuff, adding in some custom devices, Nest, IP Cams, Amazon Echo, and linking in my Arch server for various uses. 

Tendril looks very interesting, thanks for pointing it out!
